config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    root 'bulletins#index'
    resources :bulletins, except: %i[destroy] do
      member do
        patch :to_moderate
        patch :archive
      end
    end

    scope module: :profile do
      get 'profile', to: 'home#index'
    end

    namespace :admin do
      root 'home#index'
      resources :categories, except: %i[show]
      resources :bulletins, only: %i[index] do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
    end
  end
end

app/views/layouts/web/shared/_flash.html.slim
- if flash.any?
  .my-2
    - flash.each do |level, msg|
      div class= flash_classes(level)
        = msg

app/views/layouts/web/shared/_nav.html.slim
.container-md
  = link_to root_path, class: 'd-flex align-items-center navbar-brand gap-2' do
    = image_tag asset_path('logo.png'), size: '30', alt: 'logo'
    span = t('.title')

  button.navbar-toggler(type='button' data-bs-toggle='collapse' data-bs-target='#navbarCollapse'
    aria-controls='navbarCollapse' aria-expanded='false' aria-label='Toggle navigation')
    span.navbar-toggler-icon

  .collapse.navbar-collapse.pt-2.pt-md-0.justify-content-md-between id='navbarCollapse'
    ul.navbar-nav.flex-grow-1.me-md-3
      - if signed_in?
        li.nav-item = link_to t('.my_bulletins'), profile_path,
          class: "nav-link #{'active' if current_page?(profile_path)}"

        li.nav-item = link_to t('.add_bulletin'), new_bulletin_path,
          class: "nav-link #{'active' if current_page?(new_bulletin_path)}"

        - if current_user.admin?
          li.nav-item.ms-md-auto = link_to t('.admin'), admin_root_path,
            class: "nav-link #{'active' if current_page?(admin_root_path)}"

      hr.text-white-50.my-1.d-md-none

    ul.navbar-nav

        - if signed_in?
          = form_with url: auth_logout_path, method: 'delete' do |f|
            = f.button t('.logout'), class: 'nav-link text-light w-100 d-flex'
        - else
          li.nav-item
            = form_with url: auth_request_path(:github), data: { turbo: 'false' } do |f|
              = f.button class: 'nav-link text-light w-100 d-flex' do
                i.bi.bi-github.me-2
                = t('.sign_in')