config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    root 'bulletins#index'
    resources :bulletins, except: %i[destroy] do
      member do
        patch :to_moderate
        patch :archive
      end
    end

    scope module: :profile do
      get 'profile', to: 'home#index'
    end

    namespace :admin do
      root 'home#index'
      resources :categories, except: %i[show]
      resources :bulletins, only: %i[index] do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
    end
  end
end

app/controllers/web/admin/home_controller.rb
# frozen_string_literal: true

class Web::Admin::HomeController < Web::Admin::ApplicationController
  def index
    @q = Bulletin.under_moderation
                 .order(updated_at: :desc)
                 .ransack(params[:q])

    @bulletins = @q.result.includes(:user).page(page)
    @categories = Category.order(name: :asc)
  end
end

app/controllers/web/profile/application_controller.rb
# frozen_string_literal: true

class Web::Profile::ApplicationController < Web::ApplicationController
  before_action :authenticate_user!
end

app/controllers/web/profile/home_controller.rb
# frozen_string_literal: true

class Web::Profile::HomeController < Web::Profile::ApplicationController
  def index
    @q = current_user.bulletins
                     .order(updated_at: :desc)
                     .ransack(params[:q])

    @bulletins = @q.result.page(page)
  end
end

app/views/web/profile/home/index.html.slim
.my-3.p-3.bg-body.rounded.shadow-sm
  h1.fs-4
    = t('.title')
  hr

  .mb-3
    = link_to t('.add'), new_bulletin_path

  = search_form_for @q, url: profile_path do |f|
    .row
      .col-12.col-md-5.col-lg-6
        = f.input :title_cont,
          label: false,
          hint: t('.search_by_title')
      .col-12.col-md-3.col-lg-2
        = f.input :state_eq,
          as: :select,
          collection: Bulletin.aasm.states,
          label_method: :human_name,
          value_method: :name,
          hint: t('.search_by_state'),
          label: false
      .col-12.col-md-4.d-flex.align-items-start.gap-2.gap-md-4.mb-3
        = f.button :submit, class: 'btn btn-primary flex-grow-1'
        = link_to t('reset'), profile_path, class: 'btn btn-outline-primary flex-grow-1'

  .overflow-x-scroll
    table.table.table-striped.table-hover
      thead
        tr
          th{ scope = 'col' } = sort_link @q, :title, Bulletin.human_attribute_name(:title),
                                          class: 'link-dark text-decoration-none'
          th{ scope = 'col' } = sort_link @q, :state, Bulletin.human_attribute_name(:state),
                                          class: 'link-dark text-decoration-none'
          th{ scope = 'col' } = sort_link @q, :created_at, Bulletin.human_attribute_name(:created_at),
                                          class: 'link-dark text-decoration-none'
          th{ scope = 'col' } = sort_link @q, :updated_at, Bulletin.human_attribute_name(:updated_at),
                                          class: 'link-dark text-decoration-none'
          th

      tbody
        - @bulletins.each do |bulletin|
          tr
            td = link_to bulletin.title, bulletin_path(bulletin), target: '_blank', rel: 'noopener'
            td
              span(class = state_badge_classes(bulletin.state)) = bulletin.aasm.human_state
            td = distance_of_time_in_words_to_now(bulletin.created_at)
            td = distance_of_time_in_words_to_now(bulletin.updated_at)
            td
              .d-flex.flex-nowrap.gap-2
                - if bulletin.may_be_edited?
                  = link_to t('edit'), edit_bulletin_path(bulletin)
                - if bulletin.may_to_moderate?
                  = link_to t('.to_moderate'), to_moderate_bulletin_path(bulletin), data: { turbo_method: :patch },
                    class: 'text-nowrap'
                - if bulletin.may_archive?
                  = link_to t('.archive'), archive_bulletin_path(bulletin),
                    data: { turbo_method: :patch, turbo_confirm: t('.archive_confirmation') },
                    class: 'text-nowrap link-danger'

  = paginate @bulletins, theme: 'bootstrap-5',
                         pagination_class: 'pagination flex-wrap justify-content-end',
                         nav_class: 'pt-3'