config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    root 'bulletins#index'
    resources :bulletins, except: %i[destroy] do
      member do
        patch :to_moderate
        patch :archive
      end
    end

    scope module: :profile do
      get 'profile', to: 'home#index'
    end

    namespace :admin do
      root 'home#index'
      resources :categories, except: %i[show]
      resources :bulletins, only: %i[index] do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
      end
    end
  end
end

app/views/layouts/web/admin/_admin_nav.html.slim
ul.nav.nav-underline.mb-3
  li.nav-item = link_to t('.root'), admin_root_path,
    class: "nav-link #{'active' if current_page?(admin_root_path)}"

  li.nav-item = link_to t('.categories'), admin_categories_path,
    class: "nav-link #{'active' if current_page?(admin_categories_path)}"

app/views/layouts/web/admin/_nav.html.slim
ul.nav.nav-underline.mb-3.flex-column.gap-0.flex-md-row.gap-md-3
  li.nav-item = link_to t('.under_moderation'), admin_root_path,
    class: "nav-link #{'active' if current_page?(admin_root_path)}"

  li.nav-item = link_to t('.all_bulletins'), admin_bulletins_path,
      class: "nav-link #{'active' if current_page?(admin_bulletins_path)}"

  li.nav-item = link_to t('.categories'), admin_categories_path,
    class: "nav-link #{'active' if current_page?(admin_categories_path)}"

app/views/layouts/web/admin/application.html.slim
doctype html
html lang='ru'
  head
    title = t('.title')
    meta charset='utf-8'
    meta[name='viewport' content='width=device-width,initial-scale=1']
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
    = favicon_link_tag asset_path('favicon.ico')

  body.bg-body-tertiary.pt-5
    header.navbar.navbar-expand-md.fixed-top.navbar-dark.bg-dark
      = render 'layouts/web/shared/nav'

    main.container.mt-2.py-2
      = render 'layouts/web/shared/flash'

      .my-3.bg-body.rounded.shadow-sm.p-3
        = render 'layouts/web/admin/nav'

        = yield